version: '3.8'

services:
  no1:
    image: paxos_em:0.1
    command: >
      python3 -u cluster_sync/no.py 1 acceptor no1 5000 5001 
      '[{"id": 1, "role" : "acceptor" , "ip_porta" : ["no1", 5000]},
        {"id": 2, "role" : "acceptor", "ip_porta": ["no2", 5002]}, 
        {"id": 3, "role" : "acceptor", "ip_porta": ["no3", 5004]}, 
        {"id": 4, "role" : "learner", "ip_porta": ["no4", 5006]}, 
        {"id": 5, "role" : "learner", "ip_porta": ["no5", 5008]}]' 3
    ports:
      - "5001:5001"
    networks:
      - paxos_network
    healthcheck:
      test: ["CMD", "python3", "-c", "import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect(('localhost', 5001))"]
      interval: 5s
      timeout: 3s
      retries: 3

  no2:
    image: paxos_em:0.1
    command: >
      python3 -u cluster_sync/no.py 2 acceptor no2 5002 5003 
      '[{"id": 1, "role" : "acceptor" , "ip_porta" : ["no1", 5000]},
        {"id": 2, "role" : "acceptor", "ip_porta": ["no2", 5002]}, 
        {"id": 3, "role" : "acceptor", "ip_porta": ["no3", 5004]}, 
        {"id": 4, "role" : "learner", "ip_porta": ["no4", 5006]}, 
        {"id": 5, "role" : "learner", "ip_porta": ["no5", 5008]}]' 3
    ports:
      - "5003:5003"
    networks:
      - paxos_network

  no3:
    image: paxos_em:0.1
    command: >
      python3 -u cluster_sync/no.py 3 acceptor no3 5004 5005 
      '[{"id": 1, "role" : "acceptor" , "ip_porta" : ["no1", 5000]},
        {"id": 2, "role" : "acceptor", "ip_porta": ["no2", 5002]}, 
        {"id": 3, "role" : "acceptor", "ip_porta": ["no3", 5004]}, 
        {"id": 4, "role" : "learner", "ip_porta": ["no4", 5006]}, 
        {"id": 5, "role" : "learner", "ip_porta": ["no5", 5008]}]' 3
    ports:
      - "5005:5005"
    networks:
      - paxos_network

  no4:
    image: paxos_em:0.1
    command: >
      python3 -u cluster_sync/no.py 4 learner no4 5006 5007 
      '[{"id": 1, "role" : "acceptor" , "ip_porta" : ["no1", 5000]},
        {"id": 2, "role" : "acceptor", "ip_porta": ["no2", 5002]}, 
        {"id": 3, "role" : "acceptor", "ip_porta": ["no3", 5004]}, 
        {"id": 4, "role" : "learner", "ip_porta": ["no4", 5006]}, 
        {"id": 5, "role" : "learner", "ip_porta": ["no5", 5008]}]' 3
    ports:
      - "5007:5007"
    networks:
      - paxos_network

  no5:
    image: paxos_em:0.1
    command: >
      python3 -u cluster_sync/no.py 5 learner no5 5008 5009 
      '[{"id": 1, "role" : "acceptor" , "ip_porta" : ["no1", 5000]},
        {"id": 2, "role" : "acceptor", "ip_porta": ["no2", 5002]}, 
        {"id": 3, "role" : "acceptor", "ip_porta": ["no3", 5004]}, 
        {"id": 4, "role" : "learner", "ip_porta": ["no4", 5006]}, 
        {"id": 5, "role" : "learner", "ip_porta": ["no5", 5008]}]' 3
    ports:
      - "5009:5009"
    networks:
      - paxos_network


networks:
  paxos_network:
    driver: bridge
